
# This is a basic workflow to help you get started with Actions

name: Flutter Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
          flutter-version: '3.0.0'
          channel: 'stable'
    - name: Checking Flutter Version
      run: flutter --version

    - name: Build Publish Getter
      run: flutter pub get

    - name: Install Peanut Activate
      run: dart pub global activate peanut

    - name: Create peanut
      run: |
        git init
        git config --global user.email ban.kuu@yahoo.com
        git config --global user.name BANKUU
        make peanut
        git remote add origin https://${{secrets.GH_DEPLOY}}@github.com/bankuu/bankuu-info-site.git
        git checkout -b publish
        git push origin publish -f


